import './global.css';

import { Barlow } from "next/font/google";

export const metadata = {
  title: 'Welcome to portfolio',
  description: 'Generated by create-nx-workspace',
};

const barlow = Barlow({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={barlow.className}>
      <head>

        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Ajay Chowdary Nelakurthy | My Portfolio</title>
        <meta name="title" content="Ajay Chowdary Nelakurthy | My Portfolio" />
        <meta name="description"
          content="I am Ajay Chowdary Nelakurthy. Transforming innovative ideas into seamless, user-friendly web applications. As a Frontend-focused Full Stack Engineer with 4 years of experience, I bring a holistic approach to development, prioritising clean code and captivating design." />

        <meta name="keywords" content="Ajay Chowdary Nelakurthy, Portfolio, Full Stack Engineer, Frontend Developer, Web Developer, React, JavaScript, TypeScript, Node.js, AWS, UI/UX, Software Engineer, Web Applications, Developer Portfolio, HTML5, CSS3, MongoDB, PostgreSQL, Docker, CI/CD, Next.js" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://ajaychowdary.com/" />
        <meta property="og:title" content="Ajay Chowdary Nelakurthy | My Portfolio" />
        <meta property="og:description"
          content="I am Ajay Chowdary Nelakurthy. Transforming innovative ideas into seamless, user-friendly web applications. As a Frontend-focused Full Stack Engineer with 4 years of experience, I bring a holistic approach to development, prioritising clean code and captivating design." />
        <meta property="og:image" content="/ajay.jpg" />

        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://ajaychowdary.com/" />
        <meta property="twitter:title" content="Ajay Chowdary Nelakurthy | Portfolio" />
        <meta property="twitter:description"
          content="Hey, I am Ajay Chowdary Nelakurthy. Transforming innovative ideas into seamless, user-friendly web applications. As a Frontend-focused Full Stack Engineer with 4 years of experience, I bring a holistic approach to development, prioritising clean code and captivating design." />
        <meta property="twitter:image" content="/ajay.jpg" />

        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body>{children}</body>
    </html>
  );
}
